### ISSUE TITLE
这个库还在维护么，Remove的方法有解决思路么

### ISSUE THREAD

**Issue by btxkenshin** [yishuiliunian/MRLogicInjection#1]
```
//wrong API, the method cached will cause crash, if you want to do this please remove the cached method
id MRRemoveExtendLogic(id object)
```

cached具体是指？

另外，指定logicKey去做remove的方法实际上会将所有的feature都remove掉，似乎是受注入时feature的顺序，class继承关系已经有了固定的层级，无法很好的去除么

**Comment by yishuiliunian** [comment]
类进行方法查找的时候，会将找到到的方法， 先缓存在cache中，这样下次使用该方法就不用再走方法查找的流程。如果淡出，去掉class meta中的方法记录，而不清除cache中的方法记录，下次该类的实例调用该方法的时候，就会命中 method not found直接crash。这里我在研究如何干净的去除cache还有class meta中的方法记录。目前还没有较好的解决方案。

**Comment by btxkenshin** [comment]
恩明白了，目前看来需要remove的实际场景应该很少，这个repo虽小，但对实例的行为注入是个足够好而简洁的例子，感谢

**Comment by yishuiliunian** [comment]
@btxkenshin  你打算把AOP用在什么场景
